import * as fs from 'node:fs';
import * as path from 'node:path';

/**
 * Helper to resolve consent-based storage state file path.
 *
 * **Priority:**
 * 1. Consent storageState (state/consented.{env}.{region}.json) - Generated by tests/setup/auth.setup.ts
 * 2. Auth storageState (loggedInState.{env}.json) - Generated by auth tests
 * 3. undefined - Triggers manual login or consent seeds fallback
 *
 * **Generated by:** tests/setup/auth.setup.ts (runs automatically via project dependencies)
 * **Regenerate with:** npx playwright test --project=setup
 *
 * @param {string} env - Environment (production, preprod, lab, staging)
 * @param {string} region - Region code (es, it, pt)
 * @returns {string | undefined} Path to storageState file, or undefined if none exists
 *
 * @example
 * ```typescript
 * // Cinesa Production ES
 * getConsentStorageStatePath('production', 'es')
 * // => 'state/consented.production.es.json' (if exists)
 *
 * // Cinesa Preprod ES (no consent file due to Cloudflare)
 * getConsentStorageStatePath('preprod', 'es')
 * // => undefined (triggers consent seeds fallback)
 * ```
 *
 * @see docs/adrs/0014-cookie-consent-persistence-with-storage-state.md
 * @see tests/setup/auth.setup.ts
 * @since 1.0.0
 */
export function getConsentStorageStatePath(
  env?: string,
  region: string = 'es'
): string | undefined {
  if (!env) return undefined;

  const consentPath = path.join('state', `consented.${env}.${region}.json`);

  // Priority 1: Consent storageState (from tests/setup/auth.setup.ts)
  if (fs.existsSync(consentPath)) {
    return consentPath;
  }

  // Priority 2: Auth storageState (from auth tests) - Legacy fallback
  const authPath =
    env === 'preprod'
      ? 'loggedInState.preprod.json'
      : env === 'lab'
        ? 'loggedInState.lab.json'
        : 'loggedInState.json';

  if (fs.existsSync(authPath)) {
    return authPath;
  }

  // Priority 3: No storageState available (triggers consent seeds in fixtures)
  return undefined;
}

/**
 * Helper to safely resolve storage state file path (LEGACY)
 * Only returns the path if the file exists to avoid ENOENT errors
 *
 * @deprecated Use getConsentStorageStatePath() instead for consent persistence
 */
export function getStorageStatePath(env?: string): string | undefined {
  const candidate =
    env === 'preprod'
      ? 'loggedInState.preprod.json'
      : env === 'lab'
        ? 'loggedInState.lab.json'
        : 'loggedInState.json';

  return fs.existsSync(candidate) ? candidate : undefined;
}

/**
 * UCI-specific storage state path resolver
 * Uses consent storageState with IT region
 */
export function getUCIStorageStatePath(env?: string): string | undefined {
  // Use consent-based storage state for UCI (IT region)
  return getConsentStorageStatePath(env, 'it');
}

/**
 * Cinesa-specific storage state path resolver
 * Uses consent storageState with ES region
 */
export function getCinesaStorageStatePath(env?: string): string | undefined {
  // Use consent-based storage state for Cinesa (ES region)
  return getConsentStorageStatePath(env, 'es');
}

/**
 * Cinesa Portugal-specific storage state path resolver
 * Uses consent storageState with PT region
 */
export function getCinesaPortugalStorageStatePath(
  env?: string
): string | undefined {
  // Use consent-based storage state for Cinesa Portugal (PT region)
  return getConsentStorageStatePath(env, 'pt');
}
