/**
 * PRAETOR authenticated fixtures — Cinesa España checkout with logged-in session.
 *
 * Extends standard Praetor fixtures with authenticated storageState.
 * The storageState is generated by `tests/setup/auth-login.setup.ts`.
 *
 * Usage in spec files:
 * ```ts
 * import { test, expect } from '../../../../fixtures/praetor/cinesa/playwright.authenticated.fixtures';
 * ```
 */
import { test as base } from '@playwright/test';
import { WebActions } from '../../../core/webactions/webActions';
import { createCinesaContext } from '../../shared/contextFactory';
import { getAuthenticatedStorageStatePath } from '../../../config/projects/storageState.helper';
import { PraetorSeatPicker } from '../../../pageObjectsManagers/praetor/cinesa/checkout/seatPicker/seatPicker.page';
import { PraetorLogin } from '../../../pageObjectsManagers/praetor/cinesa/checkout/login/login.page';
import { PraetorTicketPicker } from '../../../pageObjectsManagers/praetor/cinesa/checkout/ticketPicker/ticketPicker.page';
import { PraetorBar } from '../../../pageObjectsManagers/praetor/cinesa/checkout/bar/bar.page';
import { PraetorPurchaseSummary } from '../../../pageObjectsManagers/praetor/cinesa/checkout/purchaseSummary/purchaseSummary.page';
import { PraetorPayment } from '../../../pageObjectsManagers/praetor/cinesa/checkout/payment/payment.page';

const env = process.env.TEST_ENV || 'production';

type PraetorAuthenticatedFixtures = {
  webActions: WebActions;
  seatPicker: PraetorSeatPicker;
  loginPage: PraetorLogin;
  purchaseSummary: PraetorPurchaseSummary;
  paymentPage: PraetorPayment;
  ticketPicker: PraetorTicketPicker;
  barPage: PraetorBar;
};

export const test = base.extend<PraetorAuthenticatedFixtures>({
  // Shared context: Cloudflare + authenticated storageState
  context: async ({ browser }, use) => {
    const authStatePath = getAuthenticatedStorageStatePath(env);

    if (!authStatePath) {
      throw new Error(
        `Authenticated storageState not found for env="${env}". ` +
        `Run: TEST_ENV=${env} npx playwright test --project=auth-login-setup --headed`
      );
    }

    const context = await createCinesaContext(browser, {
      storageStatePath: authStatePath,
    });
    await use(context);
    await context.close();
  },

  // Shared WebActions instance
  webActions: async ({ page }, use) => {
    const webActions = new WebActions(page);
    await use(webActions);
  },

  // SeatPicker POM
  seatPicker: async ({ page }, use) => {
    await use(new PraetorSeatPicker(page));
  },

  // Login POM (kept for flow compatibility — skip strategy avoids actual login)
  loginPage: async ({ page }, use) => {
    await use(new PraetorLogin(page));
  },

  // TicketPicker POM
  ticketPicker: async ({ page }, use) => {
    await use(new PraetorTicketPicker(page));
  },

  // Bar POM
  barPage: async ({ page }, use) => {
    await use(new PraetorBar(page));
  },

  // PurchaseSummary POM
  purchaseSummary: async ({ page }, use) => {
    await use(new PraetorPurchaseSummary(page));
  },

  // Payment POM
  paymentPage: async ({ page }, use) => {
    await use(new PraetorPayment(page));
  },
});

export { expect } from '@playwright/test';
