/**
 * PRAETOR SeatPicker test data — environment-aware URLs and expected values.
 *
 * Showtimes are loaded dynamically from `state/showtimes.{env}.json`
 * (generated by `tests/setup/showtimes.setup.ts`).
 * Falls back to hardcoded IDs if the JSON file is not available.
 */
import * as fs from 'node:fs';
import * as path from 'node:path';
import {
  getCinesaConfig,
  CinesaEnvironment,
} from '../../../../../config/environments';
import type { ShowtimeAllocation } from '../../../../../core/services/showtimeDiscovery';

const env = (process.env.TEST_ENV as CinesaEnvironment) || 'production';
const config = getCinesaConfig(env);
const baseUrl = config.baseUrl;

/**
 * Hardcoded fallback showtimes — used when `state/showtimes.{env}.json` is missing.
 * These WILL expire. Run `npx playwright test --project=showtimes-setup` to refresh.
 */
const FALLBACK_SHOWTIMES: ShowtimeAllocation = {
  seatPicker: '138-43544',
  bar: '138-43544',
  checkout: '138-43546',
  dbox: '138-43541',
  isense: '138-43545',
  reserve1: '138-43545',
  reserve2: '138-43542',
  reserve3: '138-43539',
  reserve4: '138-43540',
};

/**
 * Loads showtime allocation from the JSON file generated by showtimes.setup.ts.
 * Returns fallback hardcoded IDs if the file doesn't exist.
 */
function loadShowtimeAllocation(): ShowtimeAllocation {
  const jsonPath = path.join('state', `showtimes.${env}.json`);
  try {
    if (fs.existsSync(jsonPath)) {
      const raw = fs.readFileSync(jsonPath, 'utf-8');
      const data = JSON.parse(raw);
      console.log(
        `[seatPicker.data] Loaded dynamic showtimes from ${jsonPath} (discovered ${data.discoveredAt})`
      );
      return data.allocation as ShowtimeAllocation;
    }
  } catch (error) {
    console.warn(
      `[seatPicker.data] Failed to read ${jsonPath}, using fallback:`,
      error
    );
  }
  console.warn(
    `[seatPicker.data] Using FALLBACK hardcoded showtimes — run 'npx playwright test --project=showtimes-setup' to refresh`
  );
  return FALLBACK_SHOWTIMES;
}

/**
 * Lab-verified showtime pool for Oasiz_ cinema.
 * @deprecated Lab showtimes expired. Use PREPROD_OASIZ_SHOWTIMES for preprod.
 */
export const OASIZ_SHOWTIMES = {
  seatPicker: '138-36863',
  ticketPicker: '138-36871',
  bar: '138-36875',
  reserve1: '138-36859',
  reserve2: '138-36877',
} as const;

/**
 * Active showtime pool for Oasiz cinema — loaded dynamically.
 * Generated by `tests/setup/showtimes.setup.ts`, falls back to hardcoded IDs.
 */
export const PREPROD_OASIZ_SHOWTIMES: ShowtimeAllocation = loadShowtimeAllocation();

/**
 * Component-test showtimes — isolated from E2E to avoid session contention.
 * Uses showtimes NOT shared with E2E_SHOWTIMES in e2e.data.ts.
 * Free IDs not used by E2E: reserve4 (138-43543), 138-43546, 138-43544.
 */
export const COMPONENT_SHOWTIMES = {
  /** Seat picker component tests — reserve4 (Sala 7, 3D Trolls) */
  seatPicker: PREPROD_OASIZ_SHOWTIMES.reserve4,
  /** Bar component tests — Sala 2, XL late Thor */
  bar: '138-43544',
  /** Login component tests — Sala 5, 3D Reclinable The Marvels */
  login: PREPROD_OASIZ_SHOWTIMES.reserve3,
  /** Ticket picker component tests — Sala 2, XL Thor */
  ticketPicker: '138-43546',
} as const;

/** @deprecated Use OASIZ_SHOWTIMES instead */
export const OASIZ_SHOWTIME_ID = OASIZ_SHOWTIMES.seatPicker;

/** Seat picker URLs */
export const seatPickerUrls = {
  oasiz: `${baseUrl}/compra/butacas/?showtimeId=${OASIZ_SHOWTIMES.seatPicker}`,
  oasizCinemaPage: `${baseUrl}/cines/oasiz_/`,
} as const;

/** Expected seat picker behavior */
export const seatPickerExpected = {
  /** Minimum number of seats expected on the page */
  minTotalSeats: 10,
  /** MCP-verified: Oasiz_ lab had 74 seats total */
  labOasizTotalSeats: 74,
  /** Seat types that should be present */
  expectedSeatTypes: ['normal', 'sofa-left', 'sofa-right'] as const,
  /** Pricing categories observed on Oasiz_ lab */
  labPricingCategories: ['LUXE', 'Recliner Extra', 'LUXE Premium'] as const,
} as const;

/** Base URL for constructing showtime URLs */
export const checkoutBaseUrl = baseUrl;
