/**
 * PRAETOR SeatPicker test data — environment-aware URLs and expected values.
 *
 * Showtimes are loaded dynamically from `state/showtimes.{env}.json`
 * (generated by `tests/setup/showtimes.setup.ts`).
 *
 * The `showtimes-setup` project is a dependency of `Praetor-Cinesa`,
 * so the JSON file is guaranteed to exist when tests run via the normal
 * Playwright dependency chain. If running tests directly without
 * dependencies, an error is thrown with instructions to generate it.
 *
 * All showtime exports use deferred proxies so module import never
 * triggers a file read — the actual I/O happens on first property
 * access (at test execution time, after dependencies have completed).
 */
import * as fs from 'node:fs';
import * as path from 'node:path';
import {
  getCinesaConfig,
  CinesaEnvironment,
} from '../../../../../config/environments';
import type { ShowtimeAllocation } from '../../../../../core/services/showtimeDiscovery';

const env = (process.env.TEST_ENV as CinesaEnvironment) || 'production';
const config = getCinesaConfig(env);
const baseUrl = config.baseUrl;

/**
 * Creates a lazily-resolved record. The factory is invoked on first
 * property access, deferring file I/O until test execution time
 * (after Playwright dependency projects have completed).
 */
export function deferredRecord<T extends object>(factory: () => T): T {
  let resolved: T | undefined;
  return new Proxy({} as T, {
    get(_, prop) {
      if (!resolved) resolved = factory();
      return Reflect.get(resolved, prop);
    },
  });
}

let _allocation: ShowtimeAllocation | null = null;

/**
 * Loads and caches showtime allocation from the JSON file.
 * Throws if the file is missing — run `showtimes-setup` project first.
 */
function resolveAllocation(): ShowtimeAllocation {
  if (_allocation) return _allocation;
  const jsonPath = path.join('state', `showtimes.${env}.json`);
  try {
    if (fs.existsSync(jsonPath)) {
      const raw = fs.readFileSync(jsonPath, 'utf-8');
      const data = JSON.parse(raw);
      console.log(
        `[seatPicker.data] Loaded dynamic showtimes from ${jsonPath} (discovered ${data.discoveredAt})`
      );
      _allocation = data.allocation as ShowtimeAllocation;
      return _allocation;
    }
  } catch (error) {
    throw new Error(
      `[seatPicker.data] Failed to read ${jsonPath}: ${error}. ` +
        `Run: TEST_ENV=${env} npx playwright test --project=showtimes-setup`
    );
  }
  throw new Error(
    `[seatPicker.data] ${jsonPath} not found. ` +
      `Run: TEST_ENV=${env} npx playwright test --project=showtimes-setup`
  );
}

/**
 * Active showtime pool for Oasiz cinema — loaded dynamically.
 * Generated by `tests/setup/showtimes.setup.ts` (dependency of Praetor-Cinesa).
 * Deferred: file is read on first property access, not at import time.
 */
export const PREPROD_OASIZ_SHOWTIMES: ShowtimeAllocation =
  deferredRecord(resolveAllocation);

/**
 * Component-test showtimes — isolated from E2E to avoid session contention.
 * Uses allocation slots NOT shared with E2E_SHOWTIMES in e2e.data.ts.
 *
 * Mapping (avoids overlap with E2E_SHOWTIMES):
 * - seatPicker → reserve4 (E2E does NOT use reserve4)
 * - bar        → bar (sequential with seatPicker in E2E, safe to share)
 * - login      → reserve3 (E2E uses as overCapacity — different test timing)
 * - ticketPicker → checkout (E2E uses for checkoutCreditCard — different spec)
 */
export const COMPONENT_SHOWTIMES = deferredRecord(() => {
  const s = resolveAllocation();
  return {
    seatPicker: s.reserve4,
    bar: s.bar,
    login: s.reserve3,
    ticketPicker: s.checkout,
  } as const;
});

/** Seat picker URLs (deferred — depends on showtime allocation) */
export const seatPickerUrls = deferredRecord(() => ({
  oasiz: `${baseUrl}/compra/butacas/?showtimeId=${resolveAllocation().seatPicker}`,
  oasizCinemaPage: `${baseUrl}/cines/oasiz_/`,
}));

/** Expected seat picker behavior */
export const seatPickerExpected = {
  /** Minimum number of seats expected on the page */
  minTotalSeats: 10,
  /** MCP-verified: Oasiz_ lab had 74 seats total */
  labOasizTotalSeats: 74,
  /** Seat types that should be present */
  expectedSeatTypes: ['normal', 'sofa-left', 'sofa-right'] as const,
  /** Pricing categories observed on Oasiz_ lab */
  labPricingCategories: ['LUXE', 'Recliner Extra', 'LUXE Premium'] as const,
} as const;

/** Base URL for constructing showtime URLs */
export const checkoutBaseUrl = baseUrl;
