export const TICKET_PICKER_SELECTORS = {
  ticketRow: '.v-ticket-picker-table-row',
  ticketDescription: '.v-ticket-picker-table-row-details__description',
  ticketTitle: '.v-ticket-picker-table-row__item .v-ticket-picker-table-row-details__description',
  ticketPrice: '.v-ticket-picker-table-row__current-price',
  quantityInput: '.v-number-input__input',
  incrementButton: '.v-number-input__button--plus',
  decrementButton: '.v-number-input__button--minus',
  confirmButton: '.order-totals-button-container .v-button, .order-totals-button',
  promoAccordionHeader: '[data-testid="accordion-header"]',
  promoAccordionContent: '.accordion-plus.open .accordion-plus__content',
  promoInput: '#v-ticket-redemption-code-form-field__code-input',
  promoComboButton: '#v-ticket-redemption-code-form-field__type-input-button',
  promoComboOptionText: '.v-dropdown-list .v-dropdown-option__text',
  promoContinueButton: '.v-form__submit-button',
};
