/**
 * PRAETOR Authenticated Checkout test data — checkout flow with logged-in session.
 *
 * Uses a pre-authenticated storageState generated by `tests/setup/auth-login.setup.ts`.
 * The session skips the login step in the checkout flow.
 */
import {
  getCinesaConfig,
  CinesaEnvironment,
} from '../../../../../config/environments';
import { PREPROD_OASIZ_SHOWTIMES } from '../seatPicker/seatPicker.data';

const env = (process.env.TEST_ENV as CinesaEnvironment) || 'production';
const config = getCinesaConfig(env);
const baseUrl = config.baseUrl;

/** Base URL for constructing showtime URLs */
export const authenticatedCheckoutBaseUrl = baseUrl;

/**
 * Showtime allocation for authenticated checkout tests.
 * Uses reserve3 and reserve4 to test with different showtimes per test case.
 */
export const AUTH_SHOWTIMES = {
  /** Authenticated full flow to payment */
  fullFlow: PREPROD_OASIZ_SHOWTIMES.reserve4,
  /** Authenticated summary verification */
  summaryVerify: PREPROD_OASIZ_SHOWTIMES.reserve3,
} as const;

/** Checkout flow URLs */
export const authenticatedCheckoutUrls = {
  seatPicker: (showtimeId: string) =>
    `${baseUrl}/compra/butacas/?showtimeId=${showtimeId}`,
  tickets: `**/compra/tus-entradas/**`,
  bar: `**/compra/productos-de-bar/**`,
  purchaseSummary: `**/compra/resumen-de-tu-compra/**`,
  payment: `**/compra/pago-del-pedido/**`,
} as const;

/** Expected values for authenticated checkout assertions */
export const authenticatedCheckoutExpected = {
  /** Payment heading */
  paymentHeading: 'Pago del pedido',
  /** Summary heading */
  summaryHeading: 'Resumen de tu compra',
} as const;
